---
 - name: "install apache2"
   become: true
   apt:
     name: ["appache2"]
     state: latest
     update_cache: yes

 - name: "install index page"
   copy:
     src: index.html
     dest: /var/www/html/index.html
     backup: yes

 - name: "enable httpd"
   shell: |
     systemctl enable httpd
     systemctl start httpd
